#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "usage:"
  echo "./run <class-name>"
  exit 1
fi

class=$1

./build/ofextractcmd /opt/data_sets/UCF-101/frames_10fps/$class /opt/data_sets/UCF-101/resized_frames_10fps/$class /opt/data_sets/UCF-101/broxoptflow_10fps/$class

